### ISSUE TITLE
Issue in example.jsonld and example-normalized.jsonld

### ISSUE THREAD

**Issue by dpatil-fw** [smart-data-models/dataModel.Weather#12]
Looks like both these files are interchanged?
https://github.com/smart-data-models/dataModel.Weather/blob/master/WeatherObserved/examples/example-normalized.jsonld
https://github.com/smart-data-models/dataModel.Weather/blob/master/WeatherObserved/examples/example.jsonld

Was expecting "type": "Property" defined in the normalized version.
Please check.

**Comment by albertoabellagarcia** [comment]
you're completely right

**Comment by albertoabellagarcia** [comment]
There were also other tiny errors in the other example. Fixed and specifications updated.
