### ISSUE TITLE
Path of reference to weather model too deep for clean documentation.

### ISSUE THREAD

**Issue by DasNordlicht** [smart-data-models/dataModel.Weather#13]
I am currently creating automatic documentation from the schema.json files.
Apparently the path of the reference to the weather model is too deep.
`"$ref": "https://smart-data-models.github.io/dataModel.Weather/weather-schema.json#/definitions/Weather-Commons/allOf/1/properties"`

It is sufficient to reference only
`"$ref": "https://smart-data-models.github.io/dataModel.Weather/weather-schema.json#/definitions/Weather-Commons/`

Then the description fits and all definitions are read in.

**Comment by albertoabellagarcia** [comment]
You do not need to create the documentation (it is created automatically from the json schema, you only need to contribute the json  schema and one example, usually the normalized payload of NGSI V2. the rest is done automatically.

**Comment by DasNordlicht** [comment]
Yes, of course I don't need any documentation for the publication.
But we also document the models here automatically so that all the models we use can be viewed there.

I noticed that the link was too deep.

Our documentation page looks like this: https://addix.io/modelle/addix-smart-environment/WeatherObserved.html#tab-pane_allOf_i0

**Comment by albertoabellagarcia** [comment]
My validators don't validate the payloads without the 'deep' link because Weather-Commons is an object full of properties so this be the payloads if we want them to validate. As long as the payloads are regular properties at first level and not embedded in an object, then (although a bit ugly) we need that.

**Comment by albertoabellagarcia** [comment]
Regarding the visualization we have also testing the package for visualization of the data models with  json-schema-for-humans. It is on the queue but low priority for the moment.
