### ISSUE TITLE
Some doubts on the units and ranges in WeatherObserved model

### ISSUE THREAD

**Issue by jpnbastos** [smart-data-models/dataModel.Weather#14]
Hi! We were updating an Harvester and noticed that the Data Model add some changes and that raised a few issues. We leave three questions below that we could use some help with:

**Wind Direction:** Used to be measured with a value in degrees from 0-360. According to the most recent spec, this is now -180 to 180. Is there a reference for the measuring range and type and how to use it? 

**Wind Speed** It does not seem to be specified whether this is in m/s or km/h. Is either unit system valid, since they can be easily converted? Or should we adopt the SI units?

**uVMaxIndex** We understand that the idea here is to use the UV Index Scale from 1 to 11. However, we also store the value 0 during night time, since the sensor is sending data constantly. Is it possible to allow 0? Or to add a new attribute MeasureUVMaxIndex to store the measured value along the day?

In case of any change needed we are willing to propose it.

**Comment by albertoabellagarcia** [comment]
Regarding wind direction what we have is from -180 to +180. I cannot argue about it. If there is any standard/regulation with 0 to 360 we could change it. 
Regarding speed, units see the [last FAQ](https://smartdatamodels.org/index.php/faqs/). 
We recommend SI units but you can choose whatever you want.  
uvMaxIndex, ok, we will change it with this explanation.

**Comment by albertoabellagarcia** [comment]
The update of the data model is done.

**Comment by jpnbastos** [comment]
Hi Alberto, 

Thanks for the quick reply! Regarding, speed we agree with the SI units, it is what makes sense.

About the Wind Direction, on the previous data model version it was 0-360. 

From all I can gather 0-360 is the most used range, but I cannot find an actual European norm. Here are some references:
- https://library.wmo.int/doc_num.php?explnum_id=3177 (World Metereological Organization)
- https://en.wikipedia.org/wiki/Wind_direction (Wikipedia, I know...)

We cannot see a reference using -180 to 180 also. For us it makes less sense, since we have to do computation on the value. Also, I guess -180 is counter-clock wise? Why was it changed?


Thanks for the discussion and help. We really appreciate all this work and support!

**Comment by albertoabellagarcia** [comment]
it was changed to be consistent with the examples, then what are we going to do is to launch a new version of the model.

**Comment by albertoabellagarcia** [comment]
updated

**Comment by jpnbastos** [comment]
Perfect! Thank You!
