### ISSUE TITLE
weather json schema cannot be resolved

### ISSUE THREAD

**Issue by chicco785** [smart-data-models/dataModel.Weather#15]
https://github.com/smart-data-models/dataModel.Weather/blob/de19ea6b9797a72fd36fc1313d9b98de63c893b7/weather-schema.json#L3

https://smart-data-models.github.io/data-models/specs/Weather/weather-schema.json

**Comment by chicco785** [comment]
probably the correct id is: https://smart-data-models.github.io/dataModel.Weather/weather-schema.json (you may need to propagate this if referenced elsewhere)

**Comment by albertoabellagarcia** [comment]
You are fully right. 
Fixed. thanks. If you want to add your name to the [contributors](https://github.com/smart-data-models/dataModel.Weather/blob/master/CONTRIBUTORS.yaml) it will be welcomed. do the PR.
