### ISSUE TITLE
the model is about observed weather but includes also forecasts. shouldn't be a forecast a different model?

### ISSUE THREAD

**Issue by chicco785** [smart-data-models/dataModel.Weather#16]
https://github.com/smart-data-models/dataModel.Weather/blob/de19ea6b9797a72fd36fc1313d9b98de63c893b7/WeatherObserved/schema.json#L103

**Comment by albertoabellagarcia** [comment]
Certainly, you are right, in fact there is a data model [https://github.com/smart-data-models/dataModel.Weather/tree/master/WeatherForecast](https://github.com/smart-data-models/dataModel.Weather/tree/master/WeatherForecast)
Thanks
