### ISSUE TITLE
Add  uVIndex attribute

### ISSUE THREAD

**Issue by jaimeventura** [smart-data-models/dataModel.Weather#5]
Similar [WeatherForecast](https://github.com/FIWARE/data-models/tree/master/specs/Weather/WeatherForecast)'s  `uVIndexMax` attribute, this datamodel should allow specify observation of UV index for the period, based on the World Health Organization's UV Index measure.

So, im asking to update this.
I volunteer to work on this and issue a pull request, if there's an agreement in the update of such list.

**Comment by albertoabellagarcia** [comment]
ok, make all sense. 
Do you want to do a PR or could you send info about what are the right values for this property?
is it just a bigger than cero value or is it limited to 11?

**Comment by jaimeventura** [comment]
Hey,
About your question, its a very good one and took me to search more about it.
Reading the [World Health Organization's UV Index measure](https://www.who.int/uv/intersunprogramme/activities/uv_index/en/index1.html), "the values of the index range from zero upward". Then, it mentions the "INTERSUN programme" narrowing down the range staring at 1 and  "capped" at 11 (actually, the official representation is "11+").

The measurement can be higher that 11 (you can see [this table](https://www.who.int/uv/intersunprogramme/activities/uv_index/en/index3.html), values can go up to 13 in Australia (Darwin) or Kenya (Nairobi)). 
According to [this page](https://www.livescience.com/46701-andes-highest-uv-index-measured.html) the world record is set at 43.3, and than "high Andes in Peru, Bolivia, Chile and Argentina regularly hit UV index levels higher than 25".

My understanding is that it should be 0 (at night) or higher. If your understanding is that it should be capped at 11, then the scale proposed by the "INTERSUN programme" should be mentioned in the documentation instead (including the [weatherforecast](https://github.com/smart-data-models/dataModel.Weather/tree/master/WeatherForecast)'s). If so, you should also clarify that value 11 means "eleven or greater". Or, in a more extreme approach, the type for the atribute should be changed to `text`, to accommodate the "11+" representation.

By the way,  [weatherforecast](https://github.com/smart-data-models/dataModel.Weather/tree/master/WeatherForecast) datamodel's [schema](https://github.com/smart-data-models/dataModel.Weather/blob/master/WeatherForecast/schema.json), is enforcing to be 1 or greater.

**Comment by albertoabellagarcia** [comment]
I think that if it is possible to be up to 43.3 it does not make sense to limit it in the data model (what if we are checking weather in another planet, i.e. moon) therefore it should be corrected as minimum 0 and no maximum limit. Thanks for the weather it will be changed accordingly.

**Comment by albertoabellagarcia** [comment]
Committed changes
