### ISSUE TITLE
WeatherForecast multiple forecast time in the same entity ?

### ISSUE THREAD

**Issue by binomaiheu** [smart-data-models/dataModel.Weather#6]
I'm a little puzzled how to use the validTo and validFrom ranges w.r.t. the forecasted values. Typically when meteo forecasts are run, a timeseries is generated. e.g. the GFS runs a few times a day, same of ECMWF IFS, the timestamp for the runs corresponding in this datamodel to dateIssued i think ? However, for the same dateIssued, there are multiple forecasted values (i.e. an hourly, 3-hourly or daily timeseries of values for a given forecast horizon. Assuming i would like to represent this short timeseries of forecasts values, i would like to e.G; include a list / array of values with corresponding timestamps or ranges into the same forecast entity. Does this correspond with it's intended use ? As the examples given don't seem to indicate this. It would also require either explicitly mentioning the time intervals for the forecast, or specifying the interval at which the values are given in the array. 

I'm well aware of the other data formats normally used to represent weather forecasts such as netcdf & grib. However, I would like to use this datamodel to integrate a weather forecast at a limited number of locations into a smart city data broker. 

Thanks for any feedback !

**Comment by albertoabellagarcia** [comment]
that's an interesting issue. The context broker is designed for getting the updated info about a system in this very moment. In fact, we use other Generic enablers like Cygnus, Draco, quantum leap, and STH Comet to store it (and soon orion-ld). [check this out](https://www.fiware.org/developers/catalogue/).  From the data model point of view, it would be multiple instances of the weather forecast stored in those enablers. If a weather forecast has a period it should be valid for such period (I know that this is not very real). 
Anyhow, we could consider additional data models if there are uses cases and specific needs.
find here the [contribution manual](http://data-models.fiware.org/index.php/2020/05/15/contribution-manual/) and the [technical guidelines](https://github.com/smart-data-models/data-models/blob/master/guidelines.md).

**Comment by albertoabellagarcia** [comment]
Last but not least if you want to be informed about news on the different data models 
there are [weekly mail lists](http://data-models.fiware.org/index.php/subscriptions-page/) for the different domains of data models
