### ISSUE TITLE
wind info not present in JSON schema

### ISSUE THREAD

**Issue by benmomo** [smart-data-models/dataModel.Weather#9]
Hi,

why is 'wind' info not present in the schema (https://raw.githubusercontent.com/smart-data-models/dataModel.Weather/master/WeatherObserved/schema.json), but it appears in the examples and swagger?
Are you considering extending the model with more optional info? For example, some wind stations tend to give values every 2-5 seconds, info is somehow aggregated and one can store instantaneous, average and max values for wind and windDirection within a timeframe (e.g. 10 minutes)

**Comment by albertoabellagarcia** [comment]
Thanks for noticing. Like to receive it. This case you missed the [weather-commons](https://smart-data-models.github.io/dataModel.Weather/weather-schema.json#/definitions/Weather-Commons) include where this property and several others are included.
look to 
{
      "$ref": "https://smart-data-models.github.io/dataModel.Weather/weather-schema.json#/definitions/Weather-Commons"
    }
But I insist that this kind of mistakes can happen so thanks again for noticing.
